# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f8beab79516af74b50a9fa23fdab3f0f1daf01f889aaf12f6e21c5d13baf72af0641f0389be0fa440a061ebc6f101dbfc2b96428de8e7b0174ea4c3a9b3456

test:
  secret_key_base: e471197fb594a64eb0862e5ab161d78368f9c6875d2171c43130c8268681679f632c58891720389621ddcf7700557b1739d0d679b9527c89c084d24aeca072fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
